// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Launch = require("../Launch/Launch.bs.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function LaunchList(Props) {
  var launches = Props.launches;
  var handleShowDetails = Props.handleShowDetails;
  var display = Props.display;
  return React.createElement("ul", {
              style: {
                display: display,
                padding: "0"
              }
            }, Belt_Array.map(Belt_Array.keepMap(launches, (function (launch) {
                        return launch;
                      })), (function (launch) {
                    var id = launch.id;
                    if (id !== undefined) {
                      return React.createElement("li", {
                                  key: id
                                }, React.createElement(Launch.make, {
                                      launch: launch,
                                      handleShowDetails: handleShowDetails
                                    }));
                    } else {
                      return null;
                    }
                  })));
}

var make = LaunchList;

exports.make = make;
/* react Not a pure module */
