// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

((require("./Launch.css")));

function Launch(Props) {
  var launch = Props.launch;
  var handleShowDetails = Props.handleShowDetails;
  console.log("LAUNCH", launch);
  var links = launch.links;
  var flickr_images;
  if (links !== undefined) {
    var images = links.flickr_images;
    flickr_images = images !== undefined ? Belt_Array.keepMap(images, (function (flickr_images) {
              if (flickr_images !== undefined) {
                return flickr_images;
              }
              
            })) : [];
  } else {
    flickr_images = [];
  }
  return React.createElement("div", {
              className: "card-container"
            }, React.createElement("img", {
                  className: "launch-img",
                  alt: "",
                  src: Caml_array.caml_array_get(flickr_images, 0)
                }), React.createElement("div", {
                  className: "mission-info"
                }, Belt_Option.getWithDefault(Belt_Option.map(launch.mission_name, (function (mission_name) {
                            return React.createElement("span", {
                                        className: "mission-name"
                                      }, mission_name);
                          })), null), Belt_Option.getWithDefault(Belt_Option.map(launch.launch_date_local, (function (launch_date_local) {
                            var date = Belt_Option.getWithDefault(Js_json.decodeString(launch_date_local), "");
                            return React.createElement("span", {
                                        className: "launch-date"
                                      }, "Launch Date:" + date);
                          })), null), Belt_Option.getWithDefault(Belt_Option.map(launch.id, (function (id) {
                            return React.createElement("button", {
                                        className: "show-details-button",
                                        onClick: (function (param) {
                                            return Curry._1(handleShowDetails, id);
                                          })
                                      }, "Show Details");
                          })), null), Belt_Option.getWithDefault(Belt_Option.map(launch.launch_success, (function (launch_success) {
                            return React.createElement("h2", {
                                        className: "launch-success",
                                        style: {
                                          color: launch_success ? "green" : "red"
                                        }
                                      }, launch_success ? "Success" : "Fail");
                          })), null)));
}

var make = Launch;

exports.make = make;
/*  Not a pure module */
